{
 "title": "quick view of pods (cadvisor)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{pod=~\"simple-server.+\"}"
    }
   ]
  },
  {
   "title": "memory_usage_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " container_memory_usage_bytes{pod=~\"simple.+\"}"
    },
    {}
   ]
  },
  {
   "title": "i/o time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_io_time_seconds_total{pod=~\"simple.+\"}"
    }
   ]
  },
  {
   "title": "memory usage limit hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_failcnt{pod=~\"simple.+\"}"
    }
   ]
  },
  {
   "title": "container_processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_processes{pod=~\"simple-server.+\"}"
    }
   ]
  },
  {
   "title": "max memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{pod=~\"simple.+\"}"
    }
   ]
  }
 ]
}